apiVersion: v1
kind: Pod
metadata:
  name: long-load
spec:
  containers:
  - image: quay.io/redhattraining/long-load:v1
    name: long-load
    securityContext:
      allowPrivilegeEscalation: false
  restartPolicy: Always
