apiVersion: v1
kind: List
metadata: {}
items:
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: loadtest
      labels:
        app: loadtest
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: loadtest
      template:
        metadata:
          labels:
            app: loadtest
        spec:
          containers:
          - name: loadtest
            image: quay.io/redhattraining/loadtest:v1.0
            ports:
            - containerPort: 8080
            readinessProbe:
              failureThreshold: 3
              httpGet:
                path: /api/loadtest/v1/healthz
                port: 8080
                scheme: HTTP
              periodSeconds: 10
              successThreshold: 1
              timeoutSeconds: 1

  - apiVersion: v1
    kind: Service
    metadata:
      name: loadtest
      labels:
        app: loadtest
    spec:
      selector:
        app: loadtest
      ports:
      - name: http
        protocol: TCP
        port: 8080
        targetPort: 8080

  - apiVersion: route.openshift.io/v1
    kind: Route
    metadata:
      name: loadtest
      labels:
        app: loadtest
    spec:
      to:
        kind: Service
        name: loadtest
      port:
        targetPort: http
      tls:
        termination: edge
